spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.sdzn.seador.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
logging:
  level:
    org.springframework.web: TRACE